name: jiu_presence
description: A new Flutter project for JiuPresence.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  google_mlkit_face_detection: 0.9.0
  tflite_flutter: ^0.12.1
  syncfusion_flutter_pdf: ^34.1.33
  firebase_core: ^4.5.0
  firebase_messaging: ^16.1.2
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  camera: ^0.12.0
  cpf_cnpj_validator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/models/
